// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.4.11_magicast@0.3.5_rollup@4.30.1_typescript@5.7.2_vue@3.5.13_typescript@5.7.2_/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.13.0_magicast@0.3.5_vite@6.0.7_@types+node@20.17.12_jiti@2.4.2_sass@1.83.1_terse_imxsmedo2uqw6g7u2jl5ozil7a/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia-plugin-persistedstate+nuxt@1.2.1_@pinia+nuxt@0.4.11_magicast@0.3.5_rollup@4.30.1_types_5va4cx7xq2zzxzm2ez5m7jd53m/node_modules/@pinia-plugin-persistedstate/nuxt/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../src/plugins/errorHandler")> &
  InjectionType<typeof import("../../src/plugins/globalLoading")> &
  InjectionType<typeof import("../../src/plugins/naiveUi")> &
  InjectionType<typeof import("../../src/plugins/pinia")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.15.1_@parcel+watcher@2.5.0_@types+node@20.17.12_db0@0.2.1_eslint@9.17.0_jiti@2.4.2__io_ithzvka7k2zmo22gnewdljbdqe/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | '@nuxt/icon' | 'nuxt:checkIfLayoutUsed'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
